name: Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader
        
    - name: Test Extension Build
      run: |
        cd extensions/ai-layout
        npm install --no-audit --no-fund
        npm run build
        
    - name: Verify Files
      run: |
        ls -la extensions/ai-layout/dist/
        test -f extensions/ai-layout/dist/index.js
